### ISSUE TITLE
How can I get atoms instead of strings for the headings?

### ISSUE THREAD

**Issue by tilo** [CargoSense/ex_csv#10]

**Comment by benwilson512** [comment]
There is no built in way for two reasons:

1) arbitrary strings cannot be safely converted into atoms because atoms are not garbage collected, and this can grow the memory indefinitely
2) CSV headers are not guaranteed to be ascii, and at the moment the BEAM only handles ascii atoms.

You can easily build rows using atom keys however by doing:

```
csv
|> ExCSV.parse!(headings: true)
|> Stream.map(fn row ->
  %{name: row["name"], age: row["age]}
end)
```

**Comment by tilo** [comment]
I was aware of the issue around atoms not being garbage collected, and yes, there is a chance somebody uploads junk, but I was hoping that if an application has a limited set of allowed CSV-column names, that those could be easily validated and then converted into atoms.
The ASCII restriction of the BEAM is unfortunate :P

If an allowed list of ASCII CSV column names is handed in, then the conversion to atoms should not be a problem

**Comment by benwilson512** [comment]
```
headers = ~w(name age email)a
csv
|> ExCSV.parse!(headings: true)
|> Stream.map(fn row ->
  Map.new(headers, &{&1, Map.get(row, Atom.to_string(&1))})
end)
```

**Comment by benwilson512** [comment]
If you want to create a pr which added:

```
csv
|> ExCSV.parse!(headings: ~w(name age email)a)
```

We would happily accept it :)

**Comment by tilo** [comment]
thanks, Ben!  I'll have a look at it!
